name: Ngrok RDP

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: windows-latest  # You can change the runner if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        sudo mv ngrok /usr/local/bin
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok
      run: |
        ngrok authtoken $NGROK_AUTH_TOKEN
        ngrok tcp 3389 --region=us
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Display Ngrok Tunnel URL
      run: |
        sleep 10  # Give Ngrok some time to set up
        curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

