name: Ngrok RDC

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ngrok
      run: |
        echo "Setting up Ngrok..."
        # Path to the directory where you extracted Ngrok
        $ngrokDir = "C:\path\to\ngrok\directory"
        $env:PATH += ";$ngrokDir"
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok RDC Tunnel
      run: |
        ngrok authtoken $env:NGROK_AUTH_TOKEN
        ngrok tcp 3389 --region=us  # Specify the port for RDC and region as needed
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
